apiVersion: apps/v1
kind: Job
metadata:
  name: bsc-node-0
  labels:
    bsc-node-type: bsc-node
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bsc-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bsc-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: init-scripts
        configMap:
          name: init-scripts
          defaultMode: 0777
      - name: data-persistent-storage
        persistentVolumeClaim:
          claimName: bsc-node-data
      - name: temp-storage
        persistentVolumeClaim:
          claimName: bsc-node-temp
      containers:
      - name: init-snapshot
        image: "{{ .Values.init_image.repository }}:{{ .Values.init_image.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', "/init-scripts/load-snapshot.sh"]
        env:
          - name: GETH_CONFIG_DIRECTORY
            value: {{ .Values.geth.config_directory }}
          - name: GETH_DATA_DIRECTORY
            value: {{ .Values.geth.data_directory }}
          - name: SNAPSHOT_FILE
            value: {{ .Values.snapshot.file }}
          - name: SNAPSHOT_BUCKET
            value: {{ .Values.snapshot.bucket }}
          - name: SNAPSHOT_TEMP_DIRECTORY
            value: {{ .Values.snapshot.temp_directory }}
        volumeMounts:
          - mountPath: /init-scripts
            name: init-scripts
          - name: data-persistent-storage
            mountPath: {{ .Values.geth.data_directory }}
          - name: temp-storage
            mountPath: {{ .Values.snapshot.temp_directory }}