apiVersion: v1
kind: Service
metadata:
  name: bsc-node-0
  labels:
    {{- include "bsc-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 30311
      targetPort: 30311
      protocol: TCP
      name: node-conn
    - port: 30311
      targetPort: 30311
      protocol: UDP
      name: node-conn-udp
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: node-rcp
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: node-ws
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: metrics
  selector:
    {{- include "bsc-node.selectorLabels" . | nindent 4 }}

